{% set name = "edgedb-python" %}
{% set pypi_name = "edgedb" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/edgedb-{{ version }}.tar.gz
  sha256: 3ddbb841fe80d25ede524535dd52878cf74adae8c920e1f5dd912cddf66fe5f8

build:
  skip: true  # [py<38]
  entry_points:
    - edgedb-py=edgedb.codegen.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - certifi >=2021.5.30  # [win]

test:
  imports:
    - edgedb
  commands:
    - pip check
    - edgedb-py --help
  requires:
    - pip

about:
  home: https://github.com/edgedb/edgedb-python
  summary: EdgeDB Python driver
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - carlodri
    - neda-dtu
